-   id: apiblint
    name: apiblint
    description: Runs apiary/drafter.js validation on your .apib files
    entry: apiblint
    language: node
    types: [file, non-executable, text]
    files: ^*.apib$
    pass_filenames: true
