-   id: apiblint
    name: apiblint
    description: Runs apiary/drafter.js validation on your .apib files
    entry: apiblint
    language: node
    language_version: 12.6
    types: [file, non-executable, text]
    files: ^.+\.apib$
    pass_filenames: true
